version: "3.9"

services:
  web:
    build: .
    container_name: stock-data-web
    ports:
      - "5001:5001"  # host:container
    environment:
      FLASK_ENV: development
      ALPHA_VANTAGE_API_KEY: "HQXG2RROB6JX4YLI"
